### ISSUE TITLE
the i3 statusbar is not displayed

### ISSUE THREAD

**Issue by uNouss** [LukeSmithxyz/LARBS#101]
Hello, thank you for your great rice
I installed LARBS on a fresh installation of archlinux but I dont see the i3 bar.
Thank you in advance for your help

![](https://framapic.org/yhGsVm8vppS0/uLfUUOyX92YB)
![](https://framapic.org/hVDoEDuW1fCq/SYSsZLIFU3lk)

**Comment by LukeSmithxyz** [comment]
Could you run `xrdb -query` and show the output of that?

**Comment by uNouss** [comment]
`xrdb -query` command does not return anything

**Comment by LukeSmithxyz** [comment]
Well that's the problem then. Did you make any changes to Xresources by any chance?

Either way, you can fix it by pulling the most recent update from the repository and refreshing i3. I've temporarily changed the colors to be see without Xresources. Sorry for the inconvenience!

The status bar is actually there and working perfectly, there have just been some color problems: everything is showing up as black. LARBS is supposed to read colors from Xresources, but due to some changes, this isn't happening the right way recently. I can't really test it myself.

**Comment by uNouss** [comment]
@LukeSmithxyz thank you for your quick reply. it fix my issue.
