### ISSUE TITLE
Mod+4 starts a terminal instead of moving onto the 4th workspace

### ISSUE THREAD

**Issue by cedricbousmanne** [LukeSmithxyz/LARBS#102]
Everything's in the title - I made a fresh install yesterday based on the README, and I made no change on the config file so far.

**Comment by LukeSmithxyz** [comment]
This is due to how your keyboard language settings interact with i3. See an identical issue [here](LukeSmithxyz/voidrice/issues/211).

As [this post](https://github.com/LukeSmithxyz/voidrice/issues/211#issuecomment-460455099) notes, i3 will bind keys based on your keyboard layout, but by telling it that English is your primary language, you can still get all the proper binds while still using your preferred keyboard layout.

**Comment by dr3mro** [comment]
I use Finnish Keyboard and I had same issue was able to fix it by commenting those 2 lines from i3 config file
#bindsym $mod+apostrophe split horizontal ;; exec $term
#bindsym $mod+slash split vertical ;; exec $term
