### ISSUE TITLE
unable to make it work

### ISSUE THREAD

**Issue by vlucky** [LukeSmithxyz/LARBS#108]
Hi,

First thanks for the videos in youtube on how to install Arch linux from scratch & configuring the OS to look like your desktop .

I installed latest version of Arch linux (version 2019.03.01) today, and able to install it bare OS properly. But once tried to download script file, curl returning SSL_ERROR_SYSCALL error.

But somehow installed firefox and copied the script and created file manually and ran using bash shell.

It said there are no hidden errors, 
1. but once tried to login using newly created user, unable to login (getting authentication error), 
2. somehow logged in, but startx failing.

Could you please help me to configure my Arch Linux, so it will look like as your desktop with i3 status etc...

Thanks.

**Comment by xlxs4** [comment]
> 2. somehow logged in, but startx failing.

Please don't be vague when asking for help :)
It seems to me more than a messy installation than a LARBS problem.
If that's the case, you'd have better luck going through the [actual documentation].(https://wiki.archlinux.org/index.php/Installation_guide)
Luke's guide is probably the best there is, but it's far from perfect and it was released some time ago; plus, each and every system is different.

Links that might help:
- [Curl SSL connection problem(Arch)](https://bbs.archlinux.org/viewtopic.php?id=227520)
- [(c++)](https://stackoverflow.com/questions/15525344/ssl-connect-and-ssl-error-syscall)
- [(Manjaro)](https://forum.manjaro.org/t/sometimes-cannot-connect-to-aur-archlinux-org-ssl-error-syscall/26212/39)
- [some more c++](https://stackoverflow.com/questions/13686398/ssl-read-failing-with-ssl-error-syscall-error)

Best of luck :dagger:

**Comment by LukeSmithxyz** [comment]
Yeah as @xlxs4 says, this is not a LARBS problem, it's a problem with how you installed Arch Linux. I would try reinstalling carefully following the Arch Wiki's directions.

**Comment by awab228** [comment]
Its related to LARBS in some way , Maybe some tools or a way of configuration , because it's not working on the latest version of Arch , I got the same problem after installing the latest update few days ago , even I did full wipe everything and reinstalled , and still stuck after startx , the xorg sever window

**Comment by patosullivan** [comment]
I'm running a fully updated Arch installation (there are no versions, it's rolling release) with LARBS without issue.

This is probably going to end up being a good opportunity to learn more about your particular hardware configuration and the basics of maintaining a linux system.

**Comment by awab228** [comment]
I know it's rolling release , that's why said after last update , I was using LARBS for more than 2 or 3 month now , but the last system upgrade broke something and the system gets stuck at xorg sever loading , I did full wipe and everything was working fine I was Able to login again , but after installing LARBS again , the same thing happened that's why I said maybe it's something related to the packages LARBS uses ,
