### ISSUE TITLE
Polybar was not installed

### ISSUE THREAD

**Issue by akkerman** [LukeSmithxyz/LARBS#13]
Ran the script and after some time I was able to startx.
I assume polybar was supposed to be there after reading your help file but it wasn't.

Script was run on a clean install of archlinux after following along with your youtube video + install guide on archlinux.org. 

Don't know if it's relevant but I only chose to install the Fonts and Music options.

(now running polybar-git from AUR btw)

**Comment by LukeSmithxyz** [comment]
I believe the error will be that I mistyped the locale (`/etc/locale.conf`) in the video. It should be:
```
LANG=en_US.UTF-8
```
I.e. with a `_` instead of a `-` between en and US. Change that, then recomplile polybar by running `packer -S polybar`.

It might actually be safest to totally rerun the script in case anything else failed to install (it won't take nearly as much time since it won't try to reinstall already installed programs).

**Comment by akkerman** [comment]
The locale was already correct (typed it over from wiki).
When running `packer -S polybar` I run into an error ([polybar-build-failed.txt](https://github.com/LukeSmithxyz/LARBS/files/1799758/polybar-build-failed.txt)).

Since I had installed polybar in a [different way](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages) (I didn't know about packer yet) this could be related.

I'll just do the install again and let you how it goes. When/If the bar is absent I'll use packer.

**Comment by LukeSmithxyz** [comment]
Okay, it looks like a problem with the current polybar build so I'm closing the issue. You can build the git version which should work: `packer -S polybar-git`. I you run into a different issue with that, feel free to open another issue.
