### ISSUE TITLE
dwmblocks

### ISSUE THREAD

**Issue by focus85** [LukeSmithxyz/LARBS#142]
i have two volume controller on my dwmblokcs ... 
![pic-selected-191202-1400-28](https://user-images.githubusercontent.com/17464413/69991425-3f5c6780-150d-11ea-8faf-679ae9b8977e.png)

**Comment by kronikpillow** [comment]
I have the same problem, and I wasn't able to figure out why, but I opened an issue on voidrice repo as I had other issues as well... [voidrice/#413](https://github.com/LukeSmithxyz/voidrice/issues/413)

**Comment by LukeSmithxyz** [comment]
Yeah I've had this problem, but with the mail module: I think it's an issue stemming from the end of the mpd module.

**Comment by kronikpillow** [comment]
mpd module?

I have a recordingicon module
mail module
amixer module
battery capacity module
and date and time module ... I'm confused

any suggestions on how to fix the 2 volume bars?

**Comment by kronikpillow** [comment]
@focus85 found a solution on another user dwmblocks build
you need to replace the command 

	{"🔊 ", "amixer get Master | grep -o \"\\(\\[off\\]\\|[0-9]*%\\)\"", 0, 10},
with
	{"🔊 ", "amixer get Master | tail -n1 | sed -r 's/.*\\[(.*)%\\].*/\\1/'", 0, 10},

at least this is what solved the problem for me :)

**Comment by kronikpillow** [comment]
@focus85 found a solution on another user dwmblocks build
you need to replace the command

{"🔊 ", "amixer get Master | grep -o \"\\(\\[off\\]\\|[0-9]*%\\)\"", 0, 10},
with
{"🔊 ", "amixer get Master | tail -n1 | sed -r 's/.*\\[(.*)%\\].*/\\1/'", 0, 10},

or to
{"🔊 ", "amixer get Master | tail -n1 | grep -o \"\\(\\[off\\]\\|[0-9]*%\\)\"", 0, 10},

at least this is what solved the problem for me :) both options produce the same result, I'm not skilled enough to know which one is the "proper" one, and I don't get the difference between the two as both produce the same result for me since amixer sset Master toggle doesn't work for me, I can't tell if it shows off when you mute audio ....
