### ISSUE TITLE
BSPWM support

### ISSUE THREAD

**Issue by vladdoster** [LukeSmithxyz/LARBS#146]
Hi Luke, 

Do you plan on adding BSPWM as an option in LARBS? Look forward to trying out the fib tiling of BSPWM. Thanks for all your upkeep of this system.

**Comment by jaydoc** [comment]
I have the same question too. Especially given that Luke seems to have switched to using bspwm instead of i3.

**Comment by Segdon** [comment]
I concur

**Comment by jkbch** [comment]
I would also like to know this

**Comment by drake-newell** [comment]
I eventually just switched over myself, but it would be nice if he could put it in larbs for sure

**Comment by drake-newell** [comment]
Since it looks like Luke decided against bspwm, it is unlikely it will be added to LARBS. As such, I have started to modify the LARBS script to deploy my bspwm version of LARBS (with my own personal changes of course). If you guys really want to use bspwm now and want to check that out, it's on my gitlab:
https://gitlab.com/drakenewell/LARBS
https://gitlab.com/drakenewell/bspwm-rice

**Comment by LukeSmithxyz** [comment]
I've added my incomplete bspwm config files. You can search through them or submit PRs if you want, but I'm not really working on them right now.
