### ISSUE TITLE
dmenu closes on input

### ISSUE THREAD

**Issue by lyh970817** [LukeSmithxyz/LARBS#149]
Hi Luke, thank you first for your fantastic work! It makes my life with all settings so much easier. 

On my newly installed larbs it seems that the `dmenu` is not working. With `Mod+d`, `Mod+X` and `Mod+Shift+e` the menu closes if I press any key. I've previously installed `i3` without larbs and the dmenu was working. I'm wondering if it could be due to the fact that I have a Chinese keyboard layout?

**Comment by decantr** [comment]
Does `dmenu` work if run from the command line?

**Comment by RomanMunar** [comment]
Had this recently happen,  after i've switched distros and gone back to arch to reinstall larbs( shouldn't have switched 😪).
Anyways,  when i try to login using the tty and enter st,  it says st command not found and after i installed it,  it just stops saying not found.
It's been 2 days since it happened,  i tried it on several other arch distros manjaro, arco, archman, bluearch, and even void(not arch but thpught that it may work there).

**Comment by LukeSmithxyz** [comment]
@RomanMunar What happens if you install `st-luke-git` manually with yay?

**Comment by RomanMunar** [comment]
@LukeSmithxyz My updates are that i have installed larbs on an old laptop with arcolinux'D'(asus x200m 2013 model). Tried it on my main laptop did not work, however the i3 iso of arcolinuxb works and has similar bindings to larbs so i can stick with it for a while. 

So,  i tried larbs on,  same issue but, now i can type st and it recognizes it along with other terminal based applications like ranger ncmpcpp calcurse(forgot to say it previously did not). My speculation is that st cant be displayed.  Because non terminal applications are being displayed like brave, larbs guide.

**Comment by LukeSmithxyz** [comment]
Well I made `libxft-bgra` a hard requirement of my suckless builds, so if you have the vanilla `libxft` installed instead, that could be causing the problem.

There were some problems with the LARBS scripts a bit a go that you may've downloaded, but they should be fixed now.
