### ISSUE TITLE
Package installation error without warning

### ISSUE THREAD

**Issue by jcguu95** [LukeSmithxyz/LARBS#155]
Arch user here. Certain packages (`dunst`, `xset`,`notify-send`,..?) were not installed correctly by `LARBS`. As a result, X server failed to launch and user could not login properly. This is due to unknown trust arch signature -- see [this issue](https://bugs.archlinux.org/task/65054). More precisely, to resolve the problem I used `pacman-key --refresh-keys` and ran `LARBS.sh` again.

I was fortunate, since I caught that error while installing `vim`. Without it, I would not have been able to solve it. I strongly suggested `LARBS` to send a warning while certain packages are not installing correctly.

**Comment by LukeSmithxyz** [comment]
Yeah it used to be that LARBS refreshed keys automatically on first run, but I took that out because it causes some problems at some point, plus, it can take a long time and 97% of the time is totally unnecessary.

I'll either readd it to the script to add some documentation saying that it should be required beforehand.
