### ISSUE TITLE
Password not being stored properly in Void 

### ISSUE THREAD

**Issue by Lburton14** [LukeSmithxyz/LARBS#177]
After completing the LARBS script, I am unable to login to the newly created user. The password is always invalid. I've tried multiple times, even using a blank password. It always returns "password invalid" and am unable to login. I checked the /etc/shadow to have a look at the passwords and it appears that for the newly created LARBS user, the password is not stored [there's no encryption].

**Comment by PlatinumClaridge** [comment]
If you create the user during the void install process, you can install LARBS on the existing user and it should work fine.

**Comment by ovinsnes** [comment]
Just did an install on Void right now using the approach mentioned by @PlatinumClaridge 
No problems

**Comment by LukeSmithxyz** [comment]
Well this might be a funny question for me to ask, but does LARBS actually work at all on Void? I know that I said I was going to make it work on Void and did start making adjustments, but I've never actually had the time to test it myself.

Do the compiled programs like st, dmenu and dwm install correctly?

To the actual issue, yeah, since Void, unlike Arch adds the user during install and also has more specific group requirements than Arch, I might just make Void users select the user to install for, rather than giving a new password and creating a new user.

**Comment by PlatinumClaridge** [comment]
It does work, though some of the packages are named differently. So I had to manually go through and change a couple that were different in the void repo. E.g. xorg-xinit is just "xinit" and I dropped xorg-server and just went with xorg-minimal. I also had to include xdg-utils manually as it wasn't pulled as a dependency.

Aside from missing curl in the base system, dmenu, dwm, and the rest compiled fine.

If you're interested, you can see some of the changes I made here:

https://github.com/PlatinumClaridge/LARBS/blob/master/larbs.sh

I stripped it down quite a bit mostly due to my limited knowledge, but it's been working on the 3 systems I've tried it on so far.

**Comment by LukeSmithxyz** [comment]
Yeah I did add curl the other day because I know Void comes without that. I can add those packages to the Void list at least.

So no problems with st or other suckless programs? I always expected them to be the most problematic because there are a bunch of devel packages that are fragmented on Void. Are you sure you had nothing else installed beforehand?

**Comment by PlatinumClaridge** [comment]
On a fresh install, I just grab curl or wget, download the script and go. Haven't run into any issues yet.

**Comment by ovinsnes** [comment]
@PlatinumClaridge hmm that's curious because my i3 void install failed to install both `st` and `dmenu`. Are you sure you didn't change anything other than what you mentioned to make them install correctly?

**Comment by PlatinumClaridge** [comment]
I removed i3, but I can't see that affecting the install of st and dmenu. You can check my [progs.csv](https://github.com/PlatinumClaridge/LARBS/blob/master/progs.csv) to be sure, but nothing comes to mind.

**Comment by PlatinumClaridge** [comment]
larbs.sh does some things with sudoers and permissions, I wonder if that could be throwing something off. I've also removed some of those functions since the void installer sets up the user.

**Comment by LukeSmithxyz** [comment]
Yeah the permissions changes are _only_ because `makepkg` on Arch categorically does not allow you to use it as root, so you have to do all this silly stuff to allow the user to run any command without a password so you can install AUR packages, then I revert it back to requiring a password.

All of that should be unnecessary on Void.

Well yeah, I did change the location of the source files for suckless programs to `~/.local/src/` recently.
