### ISSUE TITLE
latest larbs not working properly.

### ISSUE THREAD

**Issue by Abh15h3k** [LukeSmithxyz/LARBS#178]
So. yesterday i used larbs to setup i3 on my home desktop pc and it did it successfully. today i tried in on my laptop and it kept freezing while trying to install 3 packages (nerd-fonts-inconsolata, brave-bin, simple-mtpfs). I waited more than 15 mins when it was trying install those packages then i Ctrl+c out and install then using yay. installs in a minute. what i noticed was that all of those packages have an option to chose a package.

Other than that the script also fails to install st and dmenu.

I still had the script i used on my desktop and ran it on my laptop and it installed everything correctly.

**Comment by LukeSmithxyz** [comment]
Those three AUR packages _should_ take a lot of time, especially if your internet isn't so good. If it was a general AUR problem it would've halted on `gtk-theme-arc-gruvbox-git` first.

I'm testing it now. It does seem that it is downloading to yay's cache successfully but I'll see if it hangs later. Might take some time due to my non-good internet.

**Comment by Abh15h3k** [comment]
them taking a long time is only when using larbs or in general?

cause when i just use yay -S to install them. i just hit enter for everything and then it downloads and installs in less than a minute

**Comment by LukeSmithxyz** [comment]
I mean if you install it manually via yay, it's going to use the already downloaded yay cache that LARBS was downloading.

So after some time, brave and nerd fonts installed successfully, but actually, it does seem that the process halts on simple-mtpfs due to how I have the script automatically select a version to install.

It should be fixed now, but I want to find a more elegant solution long term. Thanks for bringing this to my attention.

Are you sure that st and dmenu are not installed though? All the compiled programs are working fine for me now.

**Comment by Abh15h3k** [comment]
just tried to run the script after cloning the git. now it locks up on brave-bin

**Comment by Abh15h3k** [comment]
while installing brave-bin. it gives a 1-7 choice for font. and if I press y the hit enter. it doesn't go through. maybe that's the issue?

**Comment by Abh15h3k** [comment]
what should work is 
`yes '' | sudo ....` 

it's yes followed by 2 single quotes. for outputting newline

**Comment by LukeSmithxyz** [comment]
Oh, that's what it is. I see. I had fonts preinstalled when I reinstalled brave. Okay I'll fix this in a bit.

To be clear, the reason I use `yes |` instead of `--noconfirm` is for `libxft-bgra`, which will have to receive a `y` because it will conflict with the preinstalled `libxft`, but I think I'm just going to have to have the script install this specially since it looks like `yes` will just not get the perfect combination with all package choices.

**Comment by Abh15h3k** [comment]
That makes sense. let me know if i should close the issue

**Comment by LukeSmithxyz** [comment]
Okay. It should be fixed now. AUR installation has been returned to the command used without fail before the change earlier this week.

`libxft-bgra` is now installed uniquely at the end with `yes |` as required, while everything else is installed with `--noconfirm` as worked beforehand.

**Comment by Abh15h3k** [comment]
ok. so i tried the latest script. ran it once completed successfully. but st and dmenu didnt work. ran it again. everything working st and dmenu included.

other than that you just have a typo while installing libxft-bgra. you misspelled emoji.

needing to run the script twice could be some network issue. i was trying this in a VM while the host was on a weak wifi.

**Comment by LukeSmithxyz** [comment]
I'll check it. I had recently changed some things with how the compiled
programs are installed; there might be a real problem behind it.

Thanks a lot for helping with bug-testing this by the way.

**Comment by Abh15h3k** [comment]
Your welcome.
one more thing did pop up. 
the script no longer wants to run on my laptop specifically.
As I do sudo sh larbs.sh 
n it says are you sure you are running as root and you have internet? ( using a wired Ethernet )

tried it as root user as well same thing. 

this one I believe could be something to do with my arch install specifically. do u have any idea how I can debug this?

**Comment by Abh15h3k** [comment]
umm. in i3/config. you have `mod+Shift+a`  bound to pulsemixer. but you install alsa
