### ISSUE TITLE
Is compatibility with Void Linux and other distros worth it?

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/LARBS#182]
First off, I'm not talking about the dotfiles repo---I'd like my dotfiles to be a distro-independent as possible, but this is about LARBS as a dotfile/dependency installer.

I've said I'd like to make LARBS universal for any Linux distro, but that ends up being a lot of work and a lot of inelegance in the script for very marginal benefit. I'm thinking of focusing on core Arch-based distros instead.

## Distros that LARBS will easily be maintained for

- Arch (duh)
- Artix OpenRC
- Artix runit

For those who don't know, I use Artix runit myself, and honestly just in that group we have all the init systems covered for all those init snobs out there.

## Distros possibly worth maintaining despite the effort

- Manjaro -- More or less same repos as Arch, so same progs.csv, _but_ a lot of DE install a lot of conflicting settings, and there are a lot of DE's that people install.

Realistically speaking, maintaining for Manjaro also means dealing with much more novice users. If something goes wrong in LARBS, your average Arch user can pretty much figure any issues out on his own. But if I publicly say "oh I'm going to maintain for Manjaro," I'm going to have to be committed to doing that and documenting everything.

## Other distros

- Void -- People like Void partially because of its reminiscence to Arch with a bit more minimalism, but it requires totally different packages, packages named differently and packages that are separated out unlike in Arch. It also autoadds users on install and would in general require a lot of very little differences. It also is unique, so it has unique problems which wouldn't necessarily be the case when I'm working with only Arch distros.
- Parabola -- Uses pacman and repos like Arch, but there is a lot different since it's just free software. I advocate for Parabola and GNU distros, but there's not a huge demand---I get weekly questions from Manjaro users, but probably one or two ever from Parabola users.
- Debian/Ubuntu -- I've tossed around the idea, but I don't think there are many power users/ricers who want to use these distros despite their popularity. The AUR is hard to beat. I had the idea of making LARBS compatible with them at some point, but I've never really finalized it.

# The point

At this point, I'm leaning toward not bothering with Void and Parabola and dismissing the idea of Debian and Ubuntu, but I would like to make Manjaro work. I'd like to hear if anyone has any opinions on this. I might act soon.

I think I can make Manjaro fully compatible with just some tweaks in the dotfiles/voidrice repo. I really just need to be able to test it out here consistently with my terrible internet.

**Comment by drake-newell** [comment]
I use Parabola, but I don't think the slight differences require explicitly keeping it in mind for LARBS. As long as everything works on Arch, Parabola should just werk on LARBS for the most part, right?

**Comment by LukeSmithxyz** [comment]
Well if LARBS has ever been compatible with Void it's a total blind accident because I just put the `xbps` commands as an alternative in the script and never actually had the time and internet connection to test it lol. Obviously most of start of the script should be different for void too since it already creates users and passwords on install, etc.

I mean I guess it just seems weird to have a script that works on some Arch distros and then Void out of the blue. In principle, there's nothing especially related about them other than they're occasionally power-user choices.

**Comment by drake-newell** [comment]
@LukeSmithxyz It worked on void fine except for that compilation issue someone mentioned earlier

**Comment by PlatinumClaridge** [comment]
If you're interested, I have a fork in my repos designed purely for Void/dwm (I've removed everything Arch and i3 related). I plan on maintaining it, but if you want to use it as a separate script alongside the Arch version rather than bundle it into one big script, that works too.

**Comment by ispanos** [comment]
I think you should focus on the "**Distros that LARBS will easily be maintained for**", just because its going to be hard to support everyone from distros like Manjaro and Ubuntu. However, you might be able to make things a bit more organized by splitting the progs.csv file in to multiple files. 
I don't know if non systemd distros have that, but you could `source  /etc/os-release`, use the distro's `$ID`, and name the program files 
- arch.progs.csv
- manjaro.progs.csv
- ubuntu.progs.csv
- fedpra.progs.csv
- etc...

For Ubuntu and Fedora you will need to enable PPA's and coprs, enable extra repositories and of course make sure they are updated. So, before `installationloop`, maybe add a `case $ID in ...` to do preliminary configurations.

If someone wants to use Larbs, there is no point in using Manjaro (from my point of view). Manjaro is awesome, but for people who like the easy of a pre-configured system. Larbs does that for you. I spent 1 year on manjaro and 10 (and counting) on Arch. I have the same amount of problematic updates on both distros. One each.

As far as ubuntu, MAYBE minimal server installations could be a viable solution to avoid conflicting settings. If you add Ubuntu, the code can be easily configured to work on Fedora as well. PPAs and Coprs work in a similar way.

My script started from a fork of Larbs, but I went in a completely different direction and I'm still working on it. You could take a look to get an idea if you want. 
You need to do many things manually before you run `anergos.sh` if you are on Arch, or modify `arch_install.sh` to install arch and then run `anergos.sh`.
https://github.com/ispanos/anergos
I will add documentation only when I feel that I'm not going to change it too much again.

**Comment by loweryaustin** [comment]
As much as I loved the Manjaro i3 setup, I like yours better on Arch. I'm sure that there are a lot of Manjaro i3 users that would feel the same. Your approach is sensible and practical.

Capturing the Manjaro and Ubuntu audience is probably your smartest move if you can mitigate the support problem. There are plenty of technical users in those audiences, they're just hiding in the less technical masses.

The key to mitigating the risk of obtaining an audience that will consume all of your bandwidth via support is to set proper expectations and scope of support. Meaning:
- Specify installation requirements
- Note that the script may not work if the installation requirements are not met and support cannot be provided unless the installation requirements are strictly met
- Publish which exact variants and versions of OS are compatible
- Specify that the script *must* be run on a fresh install of a compatible OS version and variant.
- Provide instructions on how to install the OS in a way that will ensure compatibility

Trying to provide support for anything but fresh installations on specifically tested OS versions and variants would certainly become overwhelming if you were to take on a large audience.

Also, if you do plan on taking on a larger audience, I think the advertisement and documentation of feature additions/changes could be improved.

Ideally, you'd start using SemVer along with a changelog that explains to an existing user if it is worth it to upgrade to your newer version.

With versioning in place, I'd advocate having a video that concisely explains what makes LARBS better than alternatives. Something that showcases the sensible keybindings, and what makes your setup so quick and easy to use.

With each new feature or set of released features, update the video in kind.

Put the video directly within the README on github along with a summary of the features and reasons why someone would use LARBS in text.

In the process of all this it would be a good idea to either define, or re define who your target audience is, determine if that target audience would provide you with the outcome of your goals, and then adjust your goals and/or target audience as needed.

**Comment by DefunctLizard** [comment]
On a side note, I think that Open/Free/Net/MidnightBSD might be an option to consider, and not terribly difficult to port... 

But then again people who use the BSD's probably won't copy someone else's dotfiles. They typically would write them themselves.

**Comment by jcguu95** [comment]
I think the maintenance for the other distros should be done by other volunteers. It does not seem practical for me to worry too much about compatibility at this point, since `LARBS` is still growing.

The best I got from you is from your youtube channel, which pulled me into the world of (arch)linux. And I'm sure lots of people were affected in this way too. I'd suggest as the time being, bettering this part is more important. As the LARBS community grows, volunteers will come and maintain the compatibility.

**Comment by kronikpillow** [comment]
I think you should maintain compatibility with Arch distros, eg Arch & Artix (for those who do a lot of work on the init level on their desktops, trololololol) ... ubuntu, debian, parabola waste of your time and requires big maintenance, people who want to use this on debian/ubuntu can either just get the dotfiles and then go trough the process of figuring what packages they are missing to make it all work, and leave it to them ...

regarding Manjaro, who uses Manjaro? Manjaro users should realize that LARBS is a installer for Arch and that there is no big significant difference between Manjaro & Arch (yes the packages get delayed a few weeks, blablabla) but any Manjaro user should simply be recommended to install Arch with the LARBS installer, it's really easy, it's so easy, that I actually came to a point in my life, that once I get the base system setup, I dunno how to proceeds without LARBS :D you made me lazy :D

**Comment by aleksozolins** [comment]
Anyone who uses LARBS is going to have to do some creative thinking at some point to either customize to their liking or fix a small issue, so I think maybe keeping Arch install as the great filter for users is smart. Sure, you might lose "market share" without Manjaro, but in the end, you'll deal personally with more users who have put in the time to figure it out.

**Comment by PlatinumClaridge** [comment]
I don't think the concern is "market share", whatever that means. In my opinion, refusing to offer direction to people who use other distros kind of goes against what Luke talks about on his channel (e.g. "distros don't matter"). Luke does a lot of work to explain basic concepts to people who aren't hardcore Linux users, so obviously, a good portion of people who use LARBS will be beginners. So why then would it make sense to turn around and say "this only works on Arch", and refuse to give direction to people who aren't experienced with Linux?

Also, support doesn't entirely fall on Luke's shoulders. We can all contribute.

**Comment by aleksozolins** [comment]
Market share in quotes because not serious. I just meant there will be less users. I certainly understand where you're coming from and agree, support doesn't fall entirely on Luke. In terms of my own experience, I wouldn't have wanted to install LARBS before I had a few Arch installs under my belt and understood some key concepts that I figured out on my own.

Re: Distros don't matter, that's true of course, but that doesn't mean LARBS has to be distro-agnostic.

Honestly, I see both sides, but at this point, one person is doing 99% of the work. Maybe more of us contributing where we can would help open LARBS up to other distros. I guess it depends how much Luke wants to grow the project.

**Comment by PlatinumClaridge** [comment]
You missed my point. Luke has said himself that distros don't matter. So to turn around and use Arch as "the great filter" is contradictory and dare I say... elitist. I'm not saying LARBS needs to be distro agnostic, but for those of us who have taken the initiative to make LARBS work on other distros, it would be nice to share the solutions to those hurdles rather than discourage people who use other distros.

**Comment by aleksozolins** [comment]
Certainly not my intention to sound elitist. I think it's great that you have taken steps to make LARBS work on other distros and hope you'll be able contribute those additions. I still don't think a decision to keep LARBS on Arch/Artix is antithetical to the truth of distro-agnoticism.

**Comment by LukeSmithxyz** [comment]
> Luke has said himself that distros don't matter. So to turn around and use Arch as "the great filter" is contradictory and dare I say... elitist.

"Distros don't matter" because any person with a basic Linux competency can make them more or less indistinguishable. Most of the larger audience of Ubuntu or Manjaro, however simply does not have close to this level of competency. Doesn't matter if this is "elitist," it's true, and I have to make my decisions based on this.

Despite the fact that I've never really advertised these scripts as being for Manjaro, 95% of help emails about LARBS come from Manjaro users who don't know how to edit dotfiles at an extremely basic level or "break" something they don't understand.

LARBS can function as a training wheels for people like this though, in fact, maybe that's its "true" goal. It's an example of "oh, here's what your machine could function like if you designed it piece by piece from a minimal install."

**Comment by PlatinumClaridge** [comment]
And fair enough, you have to protect your time. But minimizing support requests from novice users wasn’t the focus of the original post. That’s an entirely different issue. 

You mentioned that you wanted to make LARBS compatible with Manjaro, but it seems like that would just be counterproductive.

**Comment by aleksozolins** [comment]
Defining the scope of the project more might be helpful here. My assumption has always been that LARBS was a teaching tool. As soon as I installed it and poked around a bit I was motivated to start work on my own configs. Most people who install it will probably follow a similar path. Broadening the scope beyond that will require an enormous time and energy commitment from Luke and contributors, and for what goal? To get as many people across distros as possible who agree on key-bindings? Not sure needed or worth it.

**Comment by LukeSmithxyz** [comment]
I think "teaching tool" is fair.

I think explicitly supporting Manjaro would be fine, and I'm setting
myself to it. The biggest problem is making the compatibility with the
DM and various DEs on Manjaro seamless.

**Comment by lukerb52** [comment]
I don't think Luke should have to do compatibility for stuff he doesn't use. The "L" in LARBS does stand for "Luke's". LARBS is about making it easy to get started configurating your desktop and learning GNU Linux. Don't like how LARBS does the status bar? Make BARBS (Billy's Auto-Rice Bootstrapping Scripts).

As for Manjaro, It's always worked well for me, aside from messing with the preinstalled DE. I've only switched to Arch recently. I think LARBS + Manjaro is a good first step into the whole minamilist software thing. It was for me.

**Comment by PlatinumClaridge** [comment]
Agreed. Like I said, the burden shouldn't fall on Luke to support software he doesn't use. I think the community around LARBS is large enough that it would be helpful to include documentation for other popular distros. Not necessarily adding it into the main larbs.sh script, but giving direction on how to modify it/overcome distro specific hurdles. This would reduce the volume of support emails as well as encourage people to learn.

**Comment by kronikpillow** [comment]
you obviously miss the point of what distros don't matter means mate, distros don't matter because Linux is Linux whether it is Ubuntu or Arch or Mint or Debian or whatever, the package names are different but at the core principle it is the same, LARBS is not a distro, it's a collection of dotfiles and some minimal packages with it to have a functional desktop (and even not all the packages that Luke uses are installed by default with LARBS, like mutt-wizard, like the torrent client, like stardictionary for which settings are present in the dotfiles and so on ... LARBS stands for Luke's Arch Rice Bootstrapping Script, why does he have to support all distros and answer support questions to people who don't bother to do their own research? I mean I as a 8 months LARBS user often get pissed off on some of the stupid opened issues on the voidrice repo about something very basic that is on the Arch Wiki or is easy to find a solution to without any support from Luke or LARBS users, and I even get more pissed off when I see people reopening a new issue to which a solution already exists in the opened or closed issues on the repo for which these noobs didn't bother to check other opened issues for possible solutions, and I would go totally bonkers if people kept emailing me about stupid things for which solutions are easy to find, it has nothing to do with Elitism, I am not a Linux elitist, I am a small level above a noob at this point of my Linux journey and I do think that LARBS as a bootstrap script doesn't need to support anything that Luke doesn't use simply because Luke is 1 person, and does a huge job in spreading Linux knowledge either way, if people who don't use Arch or Artix want to use his dotfiles they can clone the voidrice repo install I3 or DWM, check what packages come with LARBS and install them on their distro, and also most of these packages are actually installed by default on Ubuntu, Fedora, Manjaro, Debian, and so on.  

I was once like those Manjaro users that Luke talks about, and I was actually trolled hardcore on Manjaro forums for asking noob questions on a "noob friendly" distribution, then I moved to ArcoLinux another "noob friendly distribution where I got banned from their forums and Discord because Erik decided that I am asking too many questions... and then I was lost and decided that I really do need to do my own research but wanted some simple base functional setup from which I can start and customize to my liking so I decided to go ahead with LARBS, and thanks to LARBS and Luke, and the Arch Wiki and DuckDuckGo I studied Luke's dotfiles, player around with customizing to my liking, and I actually learned how to make my own dotfiles and manage my own minimal desktop, eventually i built my own DWM build, with my own keybindings while using Luke's setup as just a base and a quick way to install my system.

**Comment by PlatinumClaridge** [comment]
You obviously missed when I stated multiple times that I don't think Luke should have to maintain anything other than what he uses. Again, as users of LARBS (not Luke himself), we can at the very least post documentation if we get it working on another distro so that someone else who uses that distro can find fixes instead of emailing Luke.

**Comment by kronikpillow** [comment]
that I agree with, but if LARBS is supposed to support ubuntu, then it isn't LARBS, it's LURBS right? or if supposed to support Fedora then its LFRBS or LVRBS for Void 🤣🤣🤣 there is also another solution, if people want to port LARBS to other distros, they can fork LARBS and change the package names to match that distro, and then bother to provide support for that fork :)

**Comment by drake-newell** [comment]
@PlatinumClaridge I would be totally down to help make Void and/or Parabola documentation if we end up doing that.

**Comment by jcguu95** [comment]
Thanks Luke! I second for 

> LARBS can function as a training wheels for people like this though, in fact, maybe that's its "true" goal. It's an example of "oh, here's what your machine could function like if you designed it piece by piece from a minimal install."

However, I still think you should secure your time. Maintaining a software you don't use is very distracting. Perhaps paving a clearer route for them about "how to feel comfortable to switch from Manjaro to archlinux" serves the purpose as well?

**Comment by kronikpillow** [comment]
we can also do what @jcguu95  just said, help pave the path to switching from Manjaro to Arch is better then trying to make LARBS compatible with Manjaro & 10 other distros :D

**Comment by PlatinumClaridge** [comment]
> that I agree with, but if LARBS is supposed to support ubuntu, then it isn't LARBS, it's LURBS right? or if supposed to support Fedora then its LFRBS or LVRBS for Void roflroflrofl there is also another solution, if people want to port LARBS to other distros, they can fork LARBS and change the package names to match that distro, and then bother to provide support for that fork :)

well to get technical on you, it's still LARBS regardless of distro because it's "Luke's Auto-Rice Bootstrapping Script" :P 

But yeah, I have adapted LARBS to work on Void for my own personal use, but obviously, it's better to have central documentation.

**Comment by kronikpillow** [comment]
I remember luke saying in a video that its Luke's Arch Rice Bootstraping script but I might be wrong :)

**Comment by PlatinumClaridge** [comment]
@drake-newell yeah that would be awesome! Do you actively use both Void and Parabola? I use Void exclusively, so I'd definitely be down to help write documentation for it.

**Comment by drake-newell** [comment]
@PlatinumClaridge Yeah, I use Parabola on my x200 and void on my desktop.

**Comment by ProwlingPython** [comment]
While I use Void and would love to use LARBS, I think compatibility development should fall on the shoulders of contributors rather than someone who exclusively uses Arch, since that allows better management of the whole thing.

**Comment by LordRusk** [comment]
If you are going to support artix openrc and artix runit, will there be support for new (s6 was semi recently added) init systems? Since all the packages specific to each init system is just "$package-$init" (networkmanger-s6, networkmanager-runit, networkmanager-openrc, etc) it's pretty easy to add any init system support.

**Comment by LukeSmithxyz** [comment]
> I remember luke saying in a video that its Luke's Arch Rice Bootstraping script but I might be wrong :)

I've definitely called it that although officially on the website it's "auto" I think. Abbreviations don't matter. I mean people use the word LARBS 99% of the time to talk about the dotfiles and setup rather than the script anyway.



> If you are going to support artix openrc and artix runit, will there be support for new (s6 was semi recently added) init systems? Since all the packages specific to each init system is just "$package-$init" (networkmanger-s6, networkmanager-runit, networkmanager-openrc, etc) it's pretty easy to add any init system support.

Unless there's some extra installation step, you can assume it probably works already. Users are expected to have already installed the system and networking before running this script, so I don't include any of that in it.



> @PlatinumClaridge I would be totally down to help make Void and/or Parabola documentation if we end up doing that.

I will always, always accept good documentation because for the longest time, I've been way behind in it. I think the pdf readmes for both i3 and dwm is about up to date, but everything else, and system-specific testing is way behind.

You all have to understand that my internet is bad. Really bad. I can watch YouTube videos at 720p and if I leave a video uploading over night it might be up when I wake up, but doing what I used to: reinstalling Arch/other distros several times a day for testing is just not feasible.

**Comment by drake-newell** [comment]
@PlatinumClaridge FYI I encountered issues with my Parabola installation and had to switch it to Void. I'm probably gonna switch back to Parabola once they can actually manage to make a new working ISO but for now won't be able to do much testing on Parabola.

**Comment by et-8** [comment]
I also think you should focus on the distros that LARBS will easily be maintained for. I personally use it with OpenRC on Gentoo.
