### ISSUE TITLE
Brave

### ISSUE THREAD

**Issue by fuilip123** [LukeSmithxyz/LARBS#191]
Brave doesn’t work, can’t even install it
Perhaps Larbs must find an alternative

**Comment by LukeSmithxyz** [comment]
Show your error while installing. Does yay have a cache of the build?

**Comment by slappy96** [comment]
Showing brave 1.5.115-1 in the AUR
I'm currently running Brave with LARBS installed yesterday (DWM)

**Comment by kronikpillow** [comment]
works perfectly fine, except that there is a major bug in brave which makes people lose BAT, and then they don't refund you, and ignore you on the support forums ;)
https://community.brave.com/c/brave-rewards/rewards-support/73

waiting for 3 months on a refund on my lost bat, they replied 2 times asking me for some details, i gave them, and that's it, ignore since ;D

**Comment by fuilip123** [comment]
Yay have cache of brave,  #indeed 
![image](https://user-images.githubusercontent.com/62574714/77466507-ab3f4480-6e0a-11ea-9f9a-2acc159670c3.jpg)

Sorry the output is in Swedish, 

Couldn’t bother installing another browser on the computer, I took the pics with my phone, sorry

**Comment by LukeSmithxyz** [comment]
You might want to try to clean-build Brave with yay when it asks you when you run `yay -S brave-bin`. Some files might've been corrupted when you downloaded it.

**Comment by fuilip123** [comment]
Thx Luke.







Again
