### ISSUE TITLE
config of dwm and multiple monitors

### ISSUE THREAD

**Issue by tzurita** [LukeSmithxyz/LARBS#201]
the shortcut:

mod + [<||>] does not move me to the other monitor.  Was not able to figure out what keyboard combo takes me to the other monitor and vice versa.  

Sorry for the inconvenience, because I may have overlooked something but I figured ask.

**Comment by drake-newell** [comment]
Someone already asked this in the voidrice repo but I'll paste my response here:
FYI this should be in the dwm repo, but you need to add a keybinding for "focusmon" (just follow the format from the other keybinds). Same for "tagmon" if you want to send a tag to the other monitor. I would suggest binding it to left (XK_Left) and right (XK_Right) arrow to move left and right through the monitors since Luke doesn't use it for anything. Mine looks like this If you just want to copy it into your config.h. Make sure to make && sudo make install to recompile dwm after.
`{ MODKEY, XK_Left, focusmon, {.i = -1 } },	{ MODKEY, XK_Right, focusmon, {.i = +1 } },	{ MODKEY|ShiftMask, XK_Left, tagmon, {.i = -1 } },	{ MODKEY|ShiftMask, XK_Right, tagmon, {.i = +1 } },`

**Comment by tzurita** [comment]
Thank you so much, worked like a charm

**Comment by LukeSmithxyz** [comment]
Yeah I need to put default keys in for this, but I never decided which to use. I never use multiple monitors, but I know some people swear by them.
