### ISSUE TITLE
Why not just install everything with `yay`

### ISSUE THREAD

**Issue by skuzzymiglet** [LukeSmithxyz/LARBS#204]
Some AUR helpers, `yay` at least, can install from the repos and the AUR. If this is possible, I don't see why you'd have to specify AUR or repos in `progs.csv`

**Comment by LukeSmithxyz** [comment]
Marking AUR files is another way of marking distro-specific programs as
well. Originally, I don't think yay could handle the --needed flag
either, but I think that's been added (the LARBS script doesn't reflect
that).

Of course yay does take a little longer anyway because not only is it a
wrapper script, but if you run yay -S programname, it will also check
the AUR (which is laggy) to see if a package supplies programname as
well.
