### ISSUE TITLE
Not an issue, but a question

### ISSUE THREAD

**Issue by kcallis** [LukeSmithxyz/LARBS#207]
I have been dealing with the font issue for way to long. I have followed up on all of the answers from other people and still no joy. I always assumed that after the initial LARBS installation, you could not update LARBS. But I see that people pull down newer versions of LARBS (or maybe I am misunderstanding the process), so is there way to update LARBS and at the same time get my font issue squared away, or do I need to re-install Arch and then pull down the latest version of LARBS?

For instance, I noticed that @LukeSmithxyz is using DWM... Now is that a new feature of a later version of LARBS or just his choice?

**Comment by slappy96** [comment]
You can just pull down new version of LARBS.
DWM is a choice on install.  DWM / i3

That being said - not entirely sure why ~/config/fontconfig...fixes wouldn't work on existing.  Worked on DWM for me.

**Comment by LukeSmithxyz** [comment]
You can either `git pull origin master` the changes (might need to force) or you can just redownload/rerun the original LARBS script and give it the same name.

The script will only overwrite its own dotfiles and will also install any new dependencies.

Running the actual script might be better at this point because I've made a lot of changes in the last week. You'll have the choice of either dwm or i3 in the recent script.

**Comment by kcallis** [comment]
Thanks for the information... I always cloned the repository, but never did a pull. I was concerned to re-run the LARBS script and everything fell apart. So re-installing I will do!
