### ISSUE TITLE
incorect sudoers-fiel

### ISSUE THREAD

**Issue by KeyTamer** [LukeSmithxyz/LARBS#22]
the new user and the old user can't exicude sudo
error:
| user is not inthe sudoers-file

by trying to cange the file the file is Emty

**Comment by IvanStanul** [comment]
Got a same problem. It wiped out my /etc/sudoers clean.
Easily fixable by logging in as root
`su - `
And pasting sudoers file contents into:
`visudo`

**Comment by LukeSmithxyz** [comment]
I've never been able to replicate this problem. Does any have any idea what could be happening?

**Comment by LukeSmithxyz** [comment]
So I've done a little testing and it seems that this problem is likely caused by a temporary loss in internet connection. If `curl` can't connect to the sudoers file on Github to download, it will actually just erase the location it's supposed to be saving it to!

Anyway, the cause of this is either (1) those users who have had the problem have been installing LARBS with poor internet connection and curl isn't patient enough for it or (2) Github has had some outages or delays and curl isn't patient enough.

I'm going to try to make curl more forgiving or find a more consistent place to host the file than Github. I'll probably also add a strong recommendation to install via consistent ethernet, etc. or a fix if this problem occurs.

**Comment by LukeSmithxyz** [comment]
Actually I've fixed this now, just clumsily replacing and adding lines to sudoers file with coreutilites. Ugly for now, but will be more robust for users for the time being.
