### ISSUE TITLE
Issues with passwords and usernames 

### ISSUE THREAD

**Issue by larbshelp** [LukeSmithxyz/LARBS#224]
Hi, I tried installing larbs as a brute way of updating it which is similar to what was stated in the guide however it seems after creating a new password that it consistently comes up with incorrect login. I've tried the install process multiple times and it doesn't seem to be any typing errors my end.

**Comment by LukeSmithxyz** [comment]
Are you using Arch or another distro?

Has your password been changed or deleted or is it just whatever it was before?

**Comment by slappy96** [comment]
(Provided as similar experience, not as a solution)

I also have experienced this recently (yesterday and day prior).  Admittedly, it is on arch virtual box as I was trying to experiment with some DWM things.  I never got to that point though because the existing user that I had on that arch install is now un-useable.  Root is fine but if I issue passwd to change the password on the existing user it seems to accept, but does not actually change the password.

I do use larbs as primary on my laptop with no similar issues.

**Comment by VnDjW** [comment]
I had the same issue and fixed it by installing zsh:
pacman -S zsh

**Comment by slappy96** [comment]
You are correct sir @VnDjW.  Thank you for that.  Actually makes sense now that I see the issue...but I clearly didn't.

**Comment by LukeSmithxyz** [comment]
Is zsh somehow not installed after running the script? Had you manually uninstalled it?

**Comment by VnDjW** [comment]
> Is zsh somehow not installed after running the script? Had you manually uninstalled it?

I updated from a much earlier version of larbs which still used bash and i3. The script didn’t install zsh. I might have installed zsh at some point in the past, but it was certainly not installed while updating larbs.

**Comment by LukeSmithxyz** [comment]
Okay. I'm guessing it didn't install to keyring issues related to some
other open issues here. I'll need to have keyrings automatically
refreshed.
