### ISSUE TITLE
Script is stuck at "Getting rid of that retarded error beep sound..."

### ISSUE THREAD

**Issue by tiemenv** [LukeSmithxyz/LARBS#25]
Following a fresh Arch Linux install guided by Luke's Full Arch Linux Install (SAVAGE Edition!) video, I downloaded LARBS via the curl command provided on the github page and executed the script with the other command on the github page. I selected all the options except for emacs and whatever was under GIMP (I forgot the name). 

I'm running on a Lenovo B5400 laptop, connected through wifi which I enabled by it's corresponding nmcli command prior to running the script, it installed all of the 90+ programs successfully prior to the hickup (being stuck at the "Getting rid of that retarded error beep sound...") and now the only output I see is wlps4s0 deauthenticating and reauthenticating every 300 seconds. This has been going on for well over half an hour.

**Comment by LukeSmithxyz** [comment]
I'm honestly not entirely sure what this error could be; I've never
seen this. The options you chose, or even your internet shouldn't make
you hang at that point.

You should be able to just reboot and rerun the script and see if it
happens again. It won't take too long since the programs are already
installed.

You might also just want to reboot and before you run the script,run
these two commands manually and see if there's an error:

```
rmmod pcspkr
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
```

**Comment by tiemenv** [comment]
Manually entering the commands and rerunning the script resolves the issue. LARBS now ran fully and exited cleanly.

However, running startx results in "Waiting for X server to begin accepting connections", a series of dots for 2-3 minutes and finally 

xinit: giving up
xinint: unable to connect to X server: Connection refused

waiting for X server to shut down...
.......
xinit: X server slow to shut down, sending KILL signal

waiting for server to die ...
xinit: X server refuses to die

After some searching I found this is an issue that sometimes comes up when using the xf86-video-nouveau drivers, but I don't have those as I'm running on Intel integrated graphics and have the corresponding video driver installed. 

.xinitrc is present in the home directory and has the entry "exec i3"
xorg-server was installed successfully, I'm at a loss here.

**Comment by tiemenv** [comment]
I looked up what video driver I needed according to https://wiki.archlinux.org/index.php/Xorg#Driver_installation which is indeed the xf86-video-intel which I had already installed. 

Something noteworthy is that when I boot into Arch, before prompting me with a login, the tty outputs:

IPv6: ADDRCONF(NETDEV_UP): wlp4s0: link not ready
IPv6: ADDRCONF(NETDEV_UP): wlp4s0: link not ready
IPv6: ADDRCONF(NETDEV_UP): wlp4s0: link not ready
wlp4s0: authenticate with dc:53:7c:71:4c:c7
wlp4s0: send auth to dc:53:7c:71:4c:c7 (try 1/3)
wlp4s0: authenticated
wlp4s0: associate with dc:53:7c:71:4c:c7 (try 1/3)
wlp4s0: RX AssocResp from dc:53:7c:71:4c:c7 (capab=0x411 status=0 aid=3)
wlp4s0: associated
IPv6: ADDRCONF(NETDEV_CHANGE): wlp4s0: link becomes ready

then, 40 seconds later:

random: crng init done
random: 7 urandom warning(s) missed due to ratelimiting

then I have to press a key to finally go to the login prompt. After that I can login to my created user but starting startx results in the above mentioned problem. On some rare occassions (I haven't been able to determine what makes them unique) I do net get this IPv6 output and get a direct login prompt, after which startx **does work**.

**Comment by LukeSmithxyz** [comment]
Okay, interesting... I'm honestly just not sure what this could be though, especially if the IPv6 errors might be conditioning whether the X server can start... I've never seen anything quite like this.

Your problem is nearly certainly not with the LARBS script itself though, but with some bizarre interaction between your networking setup on your computer. Have you installed an Arch or other minimal desktop on this computer before?

For the record, LARBS installs NetworkManager to handle your internet connections. There might be some other package you need for some unique setup on your laptop. You might also want to just try hooking up to an ethernet port and investigating what changes that makes. It sure looks like these errors are you failing to authenticate with your own wifi.

**Comment by tiemenv** [comment]
I've tried various things by now, none of which worked and searching for my problems online yields no results leading me to believe I've fucked up somewhere in the installation process...

I'm gonna be installing Arch from scratch and perhaps trying to set up my own X server and i3 installation to see if these weird problems persist.

Thanks for all the quick and helpful replies, I'll be reporting back after I reinstalled.

**Comment by LukeSmithxyz** [comment]
So is this problem happening before installing LARBS? If it is, you'd be better served asking on another forum just because it's likely some hardware problem or extra thing you need to install.

**Comment by tiemenv** [comment]
You were right, the issue was a kernel fault with some Thinkpad Battery Extension module which it tried to load. Full thread here: 

https://bbs.archlinux.org/viewtopic.php?id=238266
