### ISSUE TITLE
Creation of ~/.larbs

### ISSUE THREAD

**Issue by nodupe** [LukeSmithxyz/LARBS#28]
Playing with i3blocks scripts provided I realized many where not working due to the fact the ~/.larbs directory was missing. I could not find where in the installation script it was supposed to be created.

**Comment by LukeSmithxyz** [comment]
Oh, silly me. Yeah, I hadn't added the `~/.larbs` directory to the dotfiles repo since its native contents aren't ready, but yeah, I guess other scripts use it. I've added it to the main repo so this shouldn't be a problem for new users.

People who already have installed it can just run `mkdir ~/.larbs`.

**Comment by nodupe** [comment]
Hi,
for the "bug" it happens when you install ttf-emojione fonts on arco linux. If you install ttf-emojione-color from AUR, the icons get better. It works well on arcolinuxd.

I've reinstalled arch from scratch and now it is working properly. Again, I had to install the rrf-emoji-color to it to work without issues.

This particular fong conflicts with noto and emojione - so i you rely on those for you theme, be aware.

Thanks for the great work, Luke!
