### ISSUE TITLE
pacman -Q artix-keyring returns error

### ISSUE THREAD

**Issue by vlamitin** [LukeSmithxyz/LARBS#288]
Hey, Luke!

Today i tried to run larbs on a fresh arch install, and found out, that it fails with error when installing keyring.
I guess this was caused by this change https://github.com/LukeSmithxyz/LARBS/commit/8222b4cb87c3dd90790813898da451de13258909#diff-947ca96db2e1e891f5b99f5985ebaf87R69

Commenting this line and rerunning larbs.sh was a workaround for me

**Comment by LukeSmithxyz** [comment]
Was this an actual failure or was it just paused for a long time?
Updating the keying can potentially be a long process.

**Comment by slavan128** [comment]
I can also confirm that issue, using older LARBS's commit fixed issue on my X201T
issue is tied up to keyring, updating keyring, or sync date and time wont helped

**Comment by vlamitin** [comment]
> Was this an actual failure or was it just paused for a long time? Updating the keying can potentially be a long process.
It was an actual failure.
Running `pacman -Q artix-keyring` manually also returns `error: package 'artix-keyring' was not found`.

Please note, that I run larbs.sh on an arch installation, not an artix one

**Comment by LukeSmithxyz** [comment]
Oh, I'm stupid. It should just be an error code issue. Since the Artix check is the last command run, the function will be considered to have failed on Arch Linux.

I've just switched the order of the commands. That should be a sufficiently lazy fix. Tell me if that's better, I don't have the opportunity to bugtest today.
