### ISSUE TITLE
Automatically delete junk like `.git` folder when done?

### ISSUE THREAD

**Issue by CecileGS** [LukeSmithxyz/LARBS#32]
It's dangerous to have push access directly from tue user home folder anyways because of the sensitive nature of some of the stuff that can go in it. The `README.md` is fine and can stay, but I find myself deleting `.git` `pic.jpg` and `LICENSE.md` every time.

On that note GNU Stow would solve some of these problems. An example dotfiles repo that uses it is https://github.com/mohabaks/dotfiles

**Comment by LukeSmithxyz** [comment]
The use of git is intentional as it allows users to update based on the remote repository and manage differences between their own local files. Users aren't going to be pushing anything to this repository so it's not an issue.

As for files like the license, well, people can just delete them on install if they want, the git folder included.

**Comment by CecileGS** [comment]
Sounds like the `.git` is a legacy solution to a XY problem then... Surely, both of these problems can be solved in a more elegant and workflow efficient way?

> update based on the remote repository
 I would rather be making a function call to a script called say `update-i3` than be calling `git pull` every time I see a new update. An additional side benefit to this is that if the user wishes, they can easily add the script to a cronjob.

> and manage differences between their own local files
How about using GNU `diff` or a `diff-i3` script?
