### ISSUE TITLE
Program suggestion: elinks

### ISSUE THREAD

**Issue by ZaxonXP** [LukeSmithxyz/LARBS#320]
It is a console web browser similar to Lynx with the additional features like possibility to define hooks which can process the websites removing unwanted content. 

Personally I use it with newsboat to read "clean" articles (without menus, ads, etc.) on a remote server.

Here is the maintained elinks version: [https://github.com/rkd77/elinks](https://github.com/rkd77/elinks)

**Comment by LukeSmithxyz** [comment]
Well lynx is only really included because it is used to generate dumps to be used as previews in lf or to be viewed in neomutt, so I don't really include it for actual use as a browser. I used to use w3m for this and I see that elinks can output to stdout as well with the `-dump` option, but I'd really only add it if it has some superiority of lynx for dumping text.

**Comment by ZaxonXP** [comment]
The superiority could be the use of hooks to filter the content of the html files or websites. :)
