### ISSUE TITLE
Vim freezing...

### ISSUE THREAD

**Issue by hindiPoohTigger** [LukeSmithxyz/LARBS#353]
...when switching window focus (dwm).
>open file in vim
>open another terminal and run commands
>eventually (usually sooner than later) running a command in said other terminal freezes vim
>switching focus back to vim, completely frozen, must be super+q'd
>pkill kills process such that it is not listed in htop or similar, yet does not terminate frozen vim instance in window

Having this issue on a clean install of larbs dwm (nvidia desktop), but also with i3 larbs on my x200. Any ideas what could be the cause of this?

**Comment by kronikpillow** [comment]
it's not vim that's freezing. it's luke's broken ST build, still don't get why people open issues on wrong repositories thou, LARBS Is just an Arch installer, the suggested issue has nothing to do with the installer, regarding VIM this should have been on /voidrice ... but the real issue is on /st ... I'v switched the terminal to alacritty since this bug is present, and on other terminals this isn't happening ...

Luke doesn't seem to be paying much attention to issues on /LARBS /dwmblocks /st
