### ISSUE TITLE
Installation fails due to zsh-fast-syntax-highlighting

### ISSUE THREAD

**Issue by pakudev** [LukeSmithxyz/LARBS#400]
[AUR Repo](https://aur.archlinux.org/packages/zsh-fast-syntax-highlighting/)

The github repo and user suddenly disappeared. Modifying the package name to [zsh-fast-syntax-highlighting-git](https://aur.archlinux.org/packages/zsh-fast-syntax-highlighting-git/) should fix the problem.

**Comment by benmordecai** [comment]
I can confirm this, but in my case, it, oddly, prompted me to login to github from the terminal and it succeeded once I did.

**Comment by pakudev** [comment]
@benmordecai Wait really? That's good to hear. I just thought it won't work, since I looked up in the aur and saw the repo got deleted and there is no "zdharma" user.

**Comment by benmordecai** [comment]
Yes that is what happened to me yesterday, however I wasn't able to really test it because I had video driver issues that were unresolved. I'll probably try again in a few days. Looks like larbs is using `zsh-fast-syntax-highlighting` instead of `zsh-fast-syntax-highlighting-git` so that could be related.
