### ISSUE TITLE
Brave not installed

### ISSUE THREAD

**Issue by yukki-14** [LukeSmithxyz/LARBS#401]
brave not installed by default

**Comment by pakudev** [comment]
Yeah recently the `progs.csv` files was modified and `brave-bin` was replaced by `brave` which shouldn't be.

**Comment by unicatte** [comment]
It appears that on Artix you can download the `brave` package from the universe repository, which is probably what inspired this change. That repository isn't enabled by default, isn't being enabled by LARBS and the package is also unavailable in Arch repositories. That's why `brave-bin` from the AUR should continue being used instead.

**Comment by kronikpillow** [comment]
the package in the universe repo is also called brave-bin ... but we really shouldn't be installing the brave package instead of brave-bin, it takes to long to compile and install

**Comment by unicatte** [comment]
> the package in the universe repo is also called brave-bin ... but we really shouldn't be installing the brave package instead of brave-bin, it takes to long to compile and install

Just to clarify, the name of the package in the universe repo was changed after I made that comment. But also the `A` tag was dropped in that commit, so there was probably no intention of compiling anything but rather to download a package from the regular repos.
