### ISSUE TITLE
Changing Volume seems doesn't work.

### ISSUE THREAD

**Issue by dankehidayat** [LukeSmithxyz/LARBS#43]
The `lmc` scripts **should** have been worked, but i don't know why i can't change the volume.
Already do `mod++` to increase the volume but still doesn't work either.

**Comment by LukeSmithxyz** [comment]
- What icon is displayed on the i3status bar for volume? The mute icon or a percentage? What is displayed when you run `pulsemixer`?
- What happens if you run a `pamixer` command manually?: `pamixer -i 20` or so? (Note that this will not update the i3bar if run without `lmc`.)
- What happens if you kill/restart Pulseaudio? `killall pulseaudio && pulseaudio --start` (as your user).

**Comment by dankehidayat** [comment]
The icon is muted before. Then `killall pulseaudio && pulseaudio --start` makes it unmuted but no percentage. And for `pamixer -i 20` it says `connection error`.

**Comment by LukeSmithxyz** [comment]
Okay, well you have some kind of pulseaudio problem... Do you have some kind of unique audio setup? It seems that Pulseaudio is either not working or isn't detecting your audio output, which it usually does fine at.

Could you run `pamixer --list-sinks`? That should show what possible sinks/outputs PA can see.

**Comment by dankehidayat** [comment]
So i just rebooting my computer now it just works! And wew the volume started at 125%.

Closing the issue now.

**Comment by LukeSmithxyz** [comment]
Okay, yeah PA can be a little wonky on first boot. Good to hear!

**Comment by pyaf** [comment]
Hey @LukeSmithxyz how can we limit the volume to be in 0-100% range only? (as of now it goes up to 150%)
