### ISSUE TITLE
Mute doesn't toggle and icon issue

### ISSUE THREAD

**Issue by ralphaaa** [LukeSmithxyz/LARBS#442]
Running fresh install on T400 laptop.

Volume up and down work fine.  Mute button works but it will only mute , it will not unmute.  There is no toggle.  If I run pamixer -t manually it toggles, the button does not.  I can unmute by using the volume buttons.

Also when I hit the mute button the status bar icon does not change.  It still shows the % volume even though it is muted.

**Comment by LukeSmithxyz** [comment]
Yeah I have the same issue on my T400 and I know it's true of older computers like the X200 as well. I think I need to add another binding to dwm because on older computers I believe the key has a different name on the backend than the ones nowadays.

Note that super+shift+m should also toggle mute and is my preferred binding.
