### ISSUE TITLE
Video playback is slowed down ?

### ISSUE THREAD

**Issue by datscyril** [LukeSmithxyz/LARBS#468]
Hello, 
I don't know why, but any video on the internet takes a minute to load.
I tried a new arch linux installation, with i3wm and nvidia drivers. The video loads instantly. I tried another new install with larbs, the video takes so long to load + the pulse mixer does not detect any of my sound devices (Dummy Output / Input only).
I have also tried to install larbs for another user, alongside my i3wm install, same results.
I don't expect anyone to solve my problem, but if anyone have a guess, I'll take it 😄

**Comment by LukeSmithxyz** [comment]
If you have some Nvidia thing, you'll probably want to check the Arch wiki for how to set that up, because LARBS doesn't do that automatically, so Xorg is probably not using your GPU properly. It's not really related to the script though.

For the audio issue, try `killall pipewire` and then restart Pipewire with `setsid -f pipewire` or something. This can be a system specific thing where sometimes it doesn't properly notice the audio card on a new system. You can consult the Arch wiki about that as well, just note that LARBS runs Pipewire and not Pulseaudio, although it has pulseaudio emulation libraries.

**Comment by datscyril** [comment]
The machine was originally configured for nvidia. Today, when you install the nvidia drivers, [there is no configuration needed](https://wiki.archlinux.org/title/NVIDIA#Xorg_configuration)

But fortunately:  I logged in as root, removed the nvidia driver, and reinstalled it, and it works now.

Thanks for your answer !
