### ISSUE TITLE
super F1 not functioning + background not loading + compton not making ST transperant.

### ISSUE THREAD

**Issue by Drunkenpanda2000** [LukeSmithxyz/LARBS#48]
super F1 not functioning + background not loading + compton not making ST transperant.

Evrything worked fine on a previous install.

after reinstall runnisng the bash.sh script again dident fix annything + no errors during install.

you can just close this if you want

**Comment by Drunkenpanda2000** [comment]
Also the bar isen't working i think some pictograms showing errors and cant open the sound config

**Comment by Drunkenpanda2000** [comment]
after a full reinstall using your arch.sh script i had the same issues.
i noticed the programs stopped installing around half way thru.
im pretty sure this is becouse packer is broken as there is a default command named packer now

**Comment by SaltyClaridge** [comment]
Yeah, LARBS has been pretty smooth since I started using about 6 weeks ago. Reinstalled it a bunch of times because I'm a tinkerer. But yesterday was the first time I had issues like this (lots of programs missing). I just took the progs.csv list and manually installed everything and then cloned the voidrice files and everything works perfectly.

**Comment by LukeSmithxyz** [comment]
Yes, as you said this is the result of a new program in the main repos called `packer`. I've patched the scripts for now, but will probably eventually change the AUR manager.
