### ISSUE TITLE
CAPS LOCK TOGGLE ISSUE 

### ISSUE THREAD

**Issue by j-6-w3n7w027h** [LukeSmithxyz/LARBS#489]
THIS IS NOT AN ISSUE WITH LARBS AFAIK. IM TYPING IN ALL CAPS AS A JOKE LOL but seriously, I love the hotkey setup out of the box that Luke has configured, works wonderfully on my laptops built-in keyboard. However, when I have my external keyboard plugged in, I experience an issue with my keyboard becoming stuck in "UPPERCASE MODE", it works as a mod key when in the default "lowercase mode," but at the same time that the mod key is triggered, it toggles into caps lock ON. The result is that the next press of the caps lock key will not work as a mod key. For example; if I hit "mod(capslock)+shift+enter" it opens the terminal, but I subsequently hit "mod(capslock)+q" it just types a capital Q into the terminal, and I haven't found any consistency in toggling caps back off. Is this a hardware issue with the keyboard itself? Any way for me to turn this toggling off completely? I have an HK GK61, and am connected via a USB hub/switch.

**Comment by LukeSmithxyz** [comment]
Yeah it's annoying since I can't put a fix in the home directory that would trigger the remaps when you plug in a new input device.

Run the `remaps` command manually to fix this. Note that `mod+f3`, even if canceled should also run the script in the background (since sometimes adding a monitor and keyboard are simultaneous with a dock).

`remaps` should map all the proper keys, but also undoes the caps lock if on.
