### ISSUE TITLE
Status Bar requires bmon

### ISSUE THREAD

**Issue by JayDSingh** [LukeSmithxyz/LARBS#503]
Hey Luke. So, if we click on the part of the status bar with the 🔺and🔻 (using `sb-nettraf`) it tries to launch bmon but will fail out-of-the-box due to it not being installed. Worked fine for me just after installing it.

**Comment by kronikpillow** [comment]
there are a lot of missing dependencies in LARBS by default, for some reason Luke refuses to accept them in a PR, yet keeps bloat like python-qdarkstyle and sc-im in the package list, which aren't even used in any of the dotfiles :D

**Comment by LukeSmithxyz** [comment]
I don't really consider this an important dependency. I don't want to pull everything these files can potentially work with. (Actually I didn't even add bmon myself and am not really happy with it).

Note that python-qdarkstyle is definitely used by any potential program the user installs so that's there for a reason. scim is probably (definitely) unnecessary and could be removed without issue (I don't even use it). I guess theoretically it's for people who use spreadsheets, but I forget what lf even uses as the default opener.

**Comment by kronikpillow** [comment]
yeah see luke, I understand your need for a minimal install, but ... not having all the dependancies of your dotfiles in your installer, means having essential functionality missing by default .... there are actually a lot of dependancies to your dotfiles that you keep refusing to include in LARBS .... but I would say it is important to supply the dotfile dependancies, because your dotfiles and LARBS is the go-to dwm testing ground for noobs who never used dwm ... I lived in your dotfiles & LARBS for 5 years before i moved on, it took me 3 years to figure out all the dependencies, and i found your dotfiles very unusable in it's barebone state .... 

but hey, that's why i maintain now a fork LARBS that includes all the batteries you keep refusing to add to the installer, but do include in your dotfiles's as essential peices to how the system works (like dependencies for lf preview)

**Comment by LukeSmithxyz** [comment]
There is no universe where this is an  "essential" dependency. Note that it's not even documented by the sb-nettraf info message and that is purposeful---because I was never happy with its addition (since the program is functionally useless as it only documents net activity *after* it's opened).

People are welcome to add unnecessary things like this to a script if it doesn't get in the way, but I am not going to force people to download a continuing larger group of programs to use features that I don't even use.
