### ISSUE TITLE
Odd behaviour when changing system state in dmenu in Arch Linux.

### ISSUE THREAD

**Issue by dawgboymike** [LukeSmithxyz/LARBS#520]
When I try to sleep, suspend, or hibernate via the Super + Backspace shortcut, the screen turns blue and will flash red when certain keys are pressed, mainly ctrl. Also the CapsLock key will randomly stop acting as another Super key and behave as a CapsLock key again. Can't find a consistent way to cause it but it happens very often. 

I'm not sure if this is an error, but I'd like to be able to make my laptop sleep instead of shut down when I close the lid, and haven't figured out where I configure that so if someone can point me in the right direction I'd appreciate it. This is all on a ThinkPad T420 running Arch.

**Comment by 2084x** [comment]
> the screen turns blue and will flash red when certain keys are pressed, mainly ctrl

This is slock running. The sysact script locks your screen before hibernating or sleeping. Type your password and hit enter to unlock. 
https://tools.suckless.org/slock/

> the CapsLock key will randomly stop acting as another Super key

This issue is being covered here: https://github.com/LukeSmithxyz/voidrice/issues/1293

If it's too annoying you can remove `remapd` from the autostart programs in `.xprofile` and add `remaps&` on a new line above autostart.

**Comment by LukeSmithxyz** [comment]
lol. slock working as intended.
