### ISSUE TITLE
^A gets inserted instead of jumping to beginning of bash line.

### ISSUE THREAD

**Issue by lukelane124** [LukeSmithxyz/LARBS#55]
This might be more appropriately logged with voidrice, but I just reinstalled Arch using LARBS.
When I attempt to go to the beginning of a line using ^A <C-a> the escape sequence just gets inserted.

Any ideas?

**Comment by LukeSmithxyz** [comment]
This is because LARBS uses [vi mode in bash by default](https://www.youtube.com/watch?v=GqoJQft5R2E). You can change this by editing `~/.inputrc`. Come to think about it, since `ctrl-a` doesn't interfere with the vim bindings, I can probably just add it in manually as I've done for `ctrl-l`. I'll make an update to that effect.

If you want to keep vi mode, but also want `ctrl-a` add two lines of `Control-a: beginning-of-line` to `~/.inputrc`, directly below the `Control-l` lines.
