### ISSUE TITLE
Weird graphical bug on shitty old atom n450, intel pineview laptop

### ISSUE THREAD

**Issue by MatthewCroughan** [LukeSmithxyz/LARBS#59]
Any help in debugging this? I am completely unfamiliar with i3, I'm a KDE noob who's only been using Linux for a year, wanted to start using i3 and liked your rice, but not on my main machine, so installed Arch on this laptop and voila, this appears. Nothing weird going on in dmesg or journalctl either.

i3 says it has some errors, when loading. It's worth noting that I actually ran larbs, overwriting an existing user on antergos which already had i3 installed. Although running the script again to make a new user doesn't change anything about this artifacting.

I'm currently unaware of how to copy and paste things in larbs, so hopefully this dusty log pic will do.

![ezgif-1-71547042d5d1](https://user-images.githubusercontent.com/26458780/48172055-3c854800-e2f6-11e8-8060-bf0fab3ea318.gif)

![img_20181108_014238](https://user-images.githubusercontent.com/26458780/48172418-b66a0100-e2f7-11e8-8d52-f8fdad63d7ee.jpg)

**Comment by LukeSmithxyz** [comment]
What happens if you `killall compton`? Compton has been causing some problems recently.

**Comment by MatthewCroughan** [comment]
@LukeSmithxyz Welp, that fixed it. Brilliant. How am I going to live without it though?

**Comment by LukeSmithxyz** [comment]
Well that isolates the problem, but I'm not sure how to proceed for your particular device. You will probably need to either install a graphics driver packages, like, say `xf86-video-intel` if you have integrated Intel graphics or change the compton backend. I don't know enough about that to tell you what to do.

You could also just disable compton from starting altogether by removing the line that starts it in the i3 config file (`~/.config/i3/config`). The only thing I use compton for is for getting transparent windows, which if you don't want them, you can just disable it. You could also install `xcompmgr` as a replacement for compton and have it start in the same place and see if you get different results.

Oh, and the i3 errors you got, this is because my dotfiles are made for i3-gaps rather than vanilla i3. You should either install i3-gaps or remove the lines causing errors.

**Comment by MatthewCroughan** [comment]
> Well that isolates the problem, but I'm not sure how to proceed for your particular device. You will probably need to either install a graphics driver packages, like, say `xf86-video-intel` if you have integrated Intel graphics or change the compton backend. I don't know enough about that to tell you what to do.

xf86-video-intel was already installed and being used, this intel chip just sucks the big one, everything seems to have lost support for it. Seriously, there's reports of Debian working for it back in Debian squeeze and wheezy, but now it simply doesn't work, video-accel, etc.

> You could also just disable compton from starting altogether by removing the line that starts it in the i3 config file (`~/.config/i3/config`). The only thing I use compton for is for getting transparent windows, which if you don't want them, you can just disable it. You could also install `xcompmgr` as a replacement for compton and have it start in the same place and see if you get different results.

This has worked wonders. Thanks a lot, replaced compton with xcompmgr

> Oh, and the i3 errors you got, this is because my dotfiles are made for i3-gaps rather than vanilla i3. You should either install i3-gaps or remove the lines causing errors.

Brilliant, this looks just like yours now, previously it was fullscreening each new window.

**Comment by LukeSmithxyz** [comment]
Okay great! Yeah I might end up changing the default composite manager to xcompmgr then. I had only needed compton just for urxvt but now that LARBS uses st as a terminal I suppose I have no more reason to rely on it.

**Comment by MatthewCroughan** [comment]
@LukeSmithxyz Just as a mediocre question, why is it that mod + shift + d irrevocably fullscreens a window? How do I get out of this, it doesn't seem to be documented.
