### ISSUE TITLE
install in manjaro i3 community edition -- no meta key works

### ISSUE THREAD

**Issue by vv111y** [LukeSmithxyz/LARBS#63]
1. installed manjaro i3 -- works
2. added manjaro xfce desktop -- works
3. ran larbs -- no response 

notes:
- apple aluminum keyboard 
- not using st: xterm, or xfce-term

things I tried:
- using stock i3 config 
- setxkbmap in: .profile, .xinitrc, .bashrc, .zshrc, .i3/config, .config/i3/config, etc
- mod1, mod4
- changing terminal

I've waisted lots of time trying to fix this. Unfortunately I took a gamble and ran LARBS before backing up. I am ready to reinstall whole system. Any help appreciated.

**Comment by LukeSmithxyz** [comment]
It's not clear to me at all what you're saying the problem is. Can you log in and boot into the graphical environment? Are you saying the keybinds don't work? Is it just the terminal keybinds or all of them? I.e. for example, can you run dmenu `mod+d`?

There's a chance that the terminal is broken after a recent update. Can you run dmenu to open xfce-term, then run st from there and see if it outputs an error?

**Comment by vv111y** [comment]
Sorry, to be clear:

- can login to i3 environment
- no key-chords work, nothing with ```mod```, except to get into the console via ```ctrl-alt-F2```

**Comment by LukeSmithxyz** [comment]
1. Okay. I assume you've been logging in in the graphical environment/display manager? In that case, could you make sure you've logged off and then log in via `ctrl-alt-F2` or something, then run `startx` and see if the result is the same.
2. Either way, open up `~/.scripts/tools/remaps` and try one of the following:
 a. Comment out the `setxkbmap` line and uncomment the commented one near it. (try the graphical environment again)
 b. Do the above, plus remove the `xcape` line. I suspect `xcape` could be causing the problem here.

**Comment by alfbarb** [comment]
Check that st terminal is installed I found the same issue and worked out
that the terminal variable was pointing to st which didn't come installed
mate?

**Comment by alfbarb** [comment]
It appeared to me as though the mod key wasn't working when in actual fact the terminal wasn't installed so mod+enter didn't do anything so it appears that was boy

**Comment by LukeSmithxyz** [comment]
Uh, okay. What is your system default keyboard? Did you set any keyboard-related settings in Manjaro's GUI?

Could you comment out the
```
sudo -n loadkeys ~/.scripts/ttymaps.kmap 2>/dev/null
```
line at the end of `~/.profile` and see if that rectifies things? I'm really confused by this problem at this point.

**Comment by LukeSmithxyz** [comment]
I had no idea that Apple keyboards required some special keyboard settings. Not surprised knowing them though. After doing a little reading it seems to me that that is nearly certainly exactly what your problem is.

You can refer to [the Arch Wiki article on Apple Keyboards](https://wiki.archlinux.org/index.php/Apple_Keyboard) which along with the linked articles might push you in the direction of solving this, but I can't backseat drive you through a solution because I'm not familiar enough with them. It probably just has to do with the Super key not mapping properly, being some different Mod button.

If the solution is something easy like that, I can add a fix, but if fixing the solution involves totally rewriting the i3 config to use unreadable keycodes, I'm not so interested.

**Comment by vv111y** [comment]
Tried another plain keyboard. Same problem. Something else is going on. 
(nb I changed ```setxkbmap``` for this keyboard)
I am randomly poking at dotfiles, scripts, and looking at larbs.sh to see what happened. Everything was working prior, but I also did system updates along the way, fwiw.  
I will retry larbs.sh see what it does. 
then I will look at doing some reinstall since I don't know enough to pinpoint the problem.

**Comment by LukeSmithxyz** [comment]
I've installed LARBS on Manjaro i3 now and it works perfectly. This is of course without a special keyboard and without installing xfce first. I suppose xfce could be the genesis of the problem as well but I can't estimate the problem.

**Comment by vv111y** [comment]
Thanks for putting in this effort Luke. 
I will work on it this weekend and get some VMs up.

**Comment by vv111y** [comment]
Finally, 
I tested on a new account and VM (with and without xfce-manjaro-*). Worked in all cases.
I updated larbs script and re-ran. Worked.  

No idea what it was, but see @chris post below for possible cause
[forum.manjaro.org](https://forum.manjaro.org/t/used-larbs-bootstrap-dotfiles-and-messed-up-i3-totally-non-responsive/67778/3?u=vv111y)

Thanks again for the help, and also for the good content you put out. Much appreciated.
