### ISSUE TITLE
zsh integration?

### ISSUE THREAD

**Issue by prankousky** [LukeSmithxyz/LARBS#78]
Hi,

I have been watching your youtube channel for quite a while now and just -finally- set up an arch machine (using debian on my home server and osx because I bought a macbook once on my laptop). Your LARBS installed fine and everything works, however, I just installed zsh as my shell and upon starting it, I get this prompt:

![screenshot](https://i.imgur.com/PJ22z0J.png)

I know that there will be some way to customize my zsh prompt (if oh-my-zsh and plugins will not do so on their own after install), but maybe someone who is even more a beginner than myself might be interested in a script or some way to have the same prompt you already implemented in bash when running zsh as an alternative shell.

If I fix this I will post the lines here, but for now I will just use bash in order to finish setting up the more important stuff first.

Cheers 👍

**Comment by LukeSmithxyz** [comment]
Looks like you're just starting zsh from bash instead of using it as the default shell. If you don't have zsh set a `$PS1` and you start it from bash, it'll just inherit bash's incompatible `$PS1` syntax.

zsh is not installed or supported by these scripts and I expect everyone who wants to change their shell knows how to deal with this kind of stuff. The furthest I've gone is link `.zprofile` to `.profile` so zsh users don't have to worry about getting the right `$PATH` and other variables, but I don't really want to spend LOC on dealing with hypothetical programs that users might install because since I don't use zsh, etc. I don't really want to maintain or enforce settings for them for others.

**Comment by Gingersnap1991** [comment]
**If you want to use zsh and never interact with bash again:**
You can set your prompt and other settings in `.zshrc` and ignore bash. The [ArchWiki](https://wiki.archlinux.org/index.php/zsh#Prompts) makes it easy to set stuff like this. If you want to keep Luke's bash-specific customizations, you'll have to copy them manually.

**If you wish to keep using both shells concurrently, or if you don't want to port the configuration:**
You may want to consider this [IndiaExchange](https://unix.stackexchange.com/questions/213036/source-bashrc-in-zsh-without-printing-any-output) thread about how to make sourcing `.bashrc` compatible. I don't use zsh myself so I can't vouch for how well it works.

And as a final tip: Use [Spectacle](https://www.spectacleapp.com/) to transform MacOS into a comfy floating WM experience 😉
